name: radonpy
channels:
  - psi4
  - conda-forge
dependencies:
  - python<=3.13
  - rdkit>=2020.03
  - mdtraj>=1.9
  - matplotlib
  - pint>0.24
  - ipykernel
  - numpy
  - pandas
  - scipy
  - psi4
  - dftd3-python
  - resp
  - pip:
    - minepy
    - -e .